// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tributrek.Infraestructura.AccesoDatos;

public partial class tri_actividades_dias
{
    public int tri_acti_dia_id { get; set; }

    public int? tri_acti_orden { get; set; }

    public int? tri_dia_itine { get; set; }

    public int? tri_acti_id { get; set; }

    public TimeOnly? tri_acti_hora_inicio { get; set; }

    public TimeOnly? tri_acti_hora_fin { get; set; }

    public virtual tri_actividades tri_acti { get; set; }

    public virtual tri_dias_itinerario tri_dia_itineNavigation { get; set; }
}