// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tributrek.Infraestructura.AccesoDatos;

public partial class tri_dias_itinerario
{
    public int tri_dia_itine { get; set; }

    public int? tri_dia_numero { get; set; }

    public int? tri_idtri_paq_iti { get; set; }

    public virtual ICollection<tri_actividades_dias> tri_actividades_dias { get; set; } = new List<tri_actividades_dias>();

    public virtual tri_paquete_itinerario tri_idtri_paq_itiNavigation { get; set; }
}