// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tributrek.Infraestructura.AccesoDatos;

public partial class tri_paquete_itinerario
{
    public int idtri_paq_iti { get; set; }

    public int? tri_paq_iti_cantidad_dias { get; set; }

    public string tri_paq_iti_descripcion { get; set; }

    public int? tri_paq_idtri_itine { get; set; }

    public DateTime? tri_paq_fecha_inicio { get; set; }

    public DateTime? tri_paq_fecha_fin { get; set; }

    public virtual ICollection<tri_dias_itinerario> tri_dias_itinerario { get; set; } = new List<tri_dias_itinerario>();

    public virtual tri_itinerario tri_paq_idtri_itineNavigation { get; set; }
}