// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tributrek.Infraestructura.AccesoDatos;

public partial class tri_nivel
{
    public int tri_niv_id { get; set; }

    public string tri_niv_dificultad { get; set; }

    public string tri_niv_estado { get; set; }

    public string tri_niv_descripcion { get; set; }

    public virtual ICollection<tri_itinerario> tri_itinerario { get; set; } = new List<tri_itinerario>();
}