// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tributrek.Infraestructura.AccesoDatos;

public partial class tri_categoria
{
    public int tri_cat_id { get; set; }

    public string tri_cat_nombre { get; set; }

    public string tri_cat_estado { get; set; }

    public DateTime? tri_fecha_creacion { get; set; }

    public DateTime? tri_fecha_mod { get; set; }

    public virtual ICollection<tri_itinerario> tri_itinerario { get; set; } = new List<tri_itinerario>();
}