// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace tributrek.Infraestructura.AccesoDatos;

public partial class tri_rol
{
    public int tri_rol_id { get; set; }

    public string tri_rol_nombre { get; set; }

    public string tri_rol_estado { get; set; }

    [JsonIgnore]

    public virtual ICollection<tri_usuario> tri_usuario { get; set; } = new List<tri_usuario>();
}