// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tributrek.Infraestructura.AccesoDatos;

public partial class tri_actividades
{
    public int tri_acti_id { get; set; }

    public string tri_acti_descripcion { get; set; }

    public string tri_acti_estado { get; set; }

    public DateTime? tri_acti_fecha_creacion { get; set; }

    public DateTime? tri_acti_fecha_mod { get; set; }

    public virtual ICollection<tri_actividades_dias> tri_actividades_dias { get; set; } = new List<tri_actividades_dias>();
}