// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace tributrek.Infraestructura.AccesoDatos;

public partial class tri_itinerario
{
    public int tri_itine_id { get; set; }

    public string tri_itine_nombre { get; set; }

    public string tri_itine_estado { get; set; }

    public DateTime? tri_itine_fecha_creacion { get; set; }

    public DateTime? tri_itine_fecha_mod { get; set; }

    public int? tri_itine_usu_id { get; set; }

    public DateOnly? tri_itine_fecha_ini { get; set; }

    public DateOnly? tri_itine_fecha_fin { get; set; }

    public TimeOnly? tri_itine_hora_inicio { get; set; }

    public int? tri_itine_cat_id { get; set; }

    public int? tri_itine_niv_id { get; set; }

    [JsonIgnore]

    public virtual tri_categoria tri_itine_cat { get; set; }

    public virtual tri_nivel tri_itine_niv { get; set; }

    public virtual tri_usuario tri_itine_usu { get; set; }

    public virtual ICollection<tri_paquete_itinerario> tri_paquete_itinerario { get; set; } = new List<tri_paquete_itinerario>();
}